/** US states and territories with NPS-managed units (for filter dropdowns). */
export const PARK_STATE_CODES = [
  'AK',
  'AL',
  'AR',
  'AS',
  'AZ',
  'CA',
  'CO',
  'CT',
  'DC',
  'DE',
  'FL',
  'GA',
  'GU',
  'HI',
  'IA',
  'ID',
  'IL',
  'IN',
  'KS',
  'KY',
  'LA',
  'MA',
  'MD',
  'ME',
  'MI',
  'MN',
  'MO',
  'MS',
  'MT',
  'NC',
  'ND',
  'NE',
  'NH',
  'NJ',
  'NM',
  'NV',
  'NY',
  'OH',
  'OK',
  'OR',
  'PA',
  'PR',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VA',
  'VI',
  'VT',
  'WA',
  'WI',
  'WV',
  'WY',
] as const

export const PARK_DESIGNATIONS = [
  'National Battlefield',
  'National Battlefield Park',
  'National Battlefield Site',
  'National Historical Park',
  'National Historical Park and Preserve',
  'National Historic Site',
  'National Historic Trail',
  'National Lakeshore',
  'National Memorial',
  'National Military Park',
  'National Monument',
  'National Monument & Preserve',
  'National Park',
  'National Park & Preserve',
  'National Parkway',
  'National Preserve',
  'National Recreation Area',
  'National Reserve',
  'National River',
  'National River & Recreation Area',
  'National Scenic Trail',
  'National Seashore',
  'National Wild and Scenic River',
  'Park',
] as const

export const PARKS_PAGE_SIZE = 24
